# BRCA 2 Concordance Script

### This script evaluates concordance between PolyPhen-2 and REVEL predictions and also compares each model’s predictions to the variant’s clinical significance reported in ClinVar

There are also concordance check between student predictions. We had each student predict with PolyPhen-2 to add redunancy into our validation and make sure everyone was getting the same results.

In [1]:
#importing the packages needed
import pandas as pd

In [ ]:
#reading in the completed file
#this file is the shared V8 BRCA2 file that everyone worked on
#you may need to save the excel spreadsheet into a csv to use for AOU.
#If mulitple tabs, just copy the desired tab into a spreadsheet and save as CSV. Only values are kept, not formating

#Reading in our data, if in AOU just need to change to read_csv with csv file or run a Pip install of Openpyxl
BRCA2_UG_AN = pd.read_excel("C:/Users/knigh/Documents/UHD MSDA/Capstone/Concordance/2026_BRCA2_ugCompleted_S3_.xlsx")
BRCA2_UG_AN.head()
#this file is pretty big dimension wise. The file I am using has 72 columns. It might we helpful to run this script in Spyder or VScode to see the data in full if needed

#Data Preview removed to comply with All of Us data user policies. You can see all the data's feature in the code block below.

In [3]:
#since the file has 72 columns, lets only save the columns we are interested in
#listing the column names
BRCA2_UG_AN.columns

Index(['locus', 'alleles', 'qc_AC', 'qc_AF', 'qc_AN', 'call_rate', 'n_het',
       'info_AC', 'info_AF', 'info_AN', 'vid', 'contig', 'position',
       'consequence', 'clinvar_classification', 'variant_type', 'ref_allele',
       'alt_allele', 'gvs_all_ac', 'gvs_all_an', 'gvs_all_af', 'gvs_all_sc',
       'dbsnp_rsid', 'revel', 'vid_alt', 'gvs_max_subpop', 'aa_change',
       'transcript', 'gene_symbol', 'gvs_max_ac', 'gvs_max_sc', 'gvs_max_an',
       'gnomad_max_subpop', 'protein_id', 'hgvsp', 'aa_extract', 'AA1', 'AA2',
       'Protein', 'Position', 'Ref_AA', 'Alt_AA',
       '(HumDiv) Polyphen Significance(S1)', 'PolyP_Score(S1)',
       'Sensitivity(S1)', 'FPR Score(S1)', 'Specificity(S1)',
       '(HumDiv) Polyphen Significance(S2)', 'PolyP_Score(S2)',
       'Sensitivity(S2)', 'FPR Score(S2)', 'Specificity(S2)',
       '(HumDiv) Polyphen Significance(S3)', 'PolyP_Score(S3)',
       'Sensitivity(S3)', 'FPR Score(S3)', 'Specificity(S3)',
       'Mutation tester(S1)', 'MT_Score(S1)', 'PhyloP Score(S1)',
       'PhastCons Score(S1)', 'Splice Site Alteration Potential(S1)',
       'Mutation tester(S2)', 'MT_Score(S2)', 'PhyloP Score(S2)',
       'PhastCons Score(S2)', 'Splice Site Alteration Potential(S2)',
       'Mutation tester(S3)', 'MT_Score(S3)', 'PhyloP Score(S3)',
       'PhastCons Score(S3)', 'Splice Site Alteration Potential(S3)'],
      dtype='object')

In [4]:
#creating a subset of only the desired columns
BRCA2_SS = BRCA2_UG_AN[["vid","consequence","clinvar_classification","variant_type","dbsnp_rsid","revel", '(HumDiv) Polyphen Significance(S1)', 'PolyP_Score(S1)',
       'Sensitivity(S1)', 'FPR Score(S1)', 'Specificity(S1)',
       '(HumDiv) Polyphen Significance(S2)', 'PolyP_Score(S2)',
       'Sensitivity(S2)', 'FPR Score(S2)', 'Specificity(S2)',
       '(HumDiv) Polyphen Significance(S3)', 'PolyP_Score(S3)',
       'Sensitivity(S3)', 'FPR Score(S3)', 'Specificity(S3)']]

#brought down to 21 columns
BRCA2_SS.head() 

#There are no AOU participant identitifers in the preview below

,vid,consequence,clinvar_classification,variant_type,dbsnp_rsid,revel,(HumDiv) Polyphen Significance(S1),PolyP_Score(S1),Sensitivity(S1),FPR Score(S1),...,(HumDiv) Polyphen Significance(S2),PolyP_Score(S2),Sensitivity(S2),FPR Score(S2),Specificity(S2),(HumDiv) Polyphen Significance(S3),PolyP_Score(S3),Sensitivity(S3),FPR Score(S3),Specificity(S3)
0,13-32316467-A-G,missense_variant,uncertain significance,SNV,rs770479195,0.045,benign,0.001,0.994,0.852,...,benign,0.001,0.994,0.852,0.148,benign,0.001,0.994,0.852,0.148
1,13-32316489-C-A,missense_variant,uncertain significance,SNV,rs1057519494,0.103,probably damaging,0.964,0.777,0.0472,...,probably damaging,0.964,0.777,0.0472,0.9528,probably damaging,0.964,0.777,0.0472,0.9528
2,13-32316513-G-A,missense_variant,"benign, likely benign",SNV,rs80358762,0.075,probably damaging,0.962,0.779,0.0478,...,probably damaging,0.962,0.779,0.0478,0.9522,probably damaging,0.962,0.779,0.0478,0.9522
3,13-32316522-A-G,missense_variant,"likely benign, uncertain significance",SNV,rs397507367,0.049,benign,0.139,0.923,0.137,...,benign,0.139,0.923,0.137,0.863,benign,0.139,0.923,0.137,0.863
4,13-32319088-A-G,missense_variant,"benign, uncertain significance",SNV,rs80359034,0.057,benign,0.007,0.965,0.246,...,benign,0.007,0.965,0.246,0.754,benign,0.007,0.965,0.246,0.754

In [5]:
#checking for NAs
BRCA2_SS.isna().sum()

#we have 65 missing clinvar classifications, 34 rsids, and many missing student entered values
#we will handle these downstream when cleaning the data

vid                                     0
consequence                             0
clinvar_classification                 65
variant_type                            0
dbsnp_rsid                             34
revel                                   0
(HumDiv) Polyphen Significance(S1)      0
PolyP_Score(S1)                         0
Sensitivity(S1)                         0
FPR Score(S1)                         298
Specificity(S1)                       357
(HumDiv) Polyphen Significance(S2)    257
PolyP_Score(S2)                       646
Sensitivity(S2)                       646
FPR Score(S2)                         786
Specificity(S2)                         0
(HumDiv) Polyphen Significance(S3)      0
PolyP_Score(S3)                         0
Sensitivity(S3)                         0
FPR Score(S3)                           0
Specificity(S3)                         0
dtype: int64

## Aligning the columns values for comparisons

In [6]:
#checking the unique values in the consequence column. Should all be variations of missense
BRCA2_SS.consequence.unique()

array(['missense_variant', 'missense_variant, splice_region_variant'],
      dtype=object)

In [7]:
#just changing all the missense to be missense_variant
BRCA2_SS.loc[BRCA2_SS["consequence"].str.contains("missense"), "consequence"] = "missense_variant"

#checking it worked
print(BRCA2_SS.consequence.unique())

#grabbing the count of missense values, should be the same as the # of rows
(BRCA2_SS['consequence']=='missense_variant').sum() #906

['missense_variant']

np.int64(906)

In [8]:
#looking at the values in the clinvar classification columns
print(BRCA2_SS.clinvar_classification.unique())

#looking at the count of the values so when we condense them, we can make sure the count was allocated correctly
BRCA2_SS["clinvar_classification"].value_counts()

['uncertain significance' 'benign, likely benign'
 'likely benign, uncertain significance' 'benign, uncertain significance'
 nan 'benign, likely benign, uncertain significance' 'benign'
 'uncertain significance, likely pathogenic, pathogenic'
 'uncertain significance, likely pathogenic'
 'benign, likely benign, uncertain significance, likely pathogenic'
 'likely benign, uncertain significance, not provided' 'likely benign'
 'likely benign, uncertain significance, pathogenic'
 'likely benign, uncertain significance, likely pathogenic'
 'benign, likely pathogenic, pathogenic' 'pathogenic'
 'benign, likely benign, likely pathogenic'
 'likely pathogenic, pathogenic']

clinvar_classification
likely benign, uncertain significance                               445
uncertain significance                                              165
benign, likely benign, uncertain significance                       136
benign, likely benign                                                53
uncertain significance, likely pathogenic, pathogenic                 6
likely benign, uncertain significance, not provided                   6
benign, uncertain significance                                        5
benign, likely benign, uncertain significance, likely pathogenic      5
uncertain significance, likely pathogenic                             4
likely benign                                                         4
benign                                                                3
likely benign, uncertain significance, pathogenic                     2
likely benign, uncertain significance, likely pathogenic              2
pathogenic                                                            2
benign, likely pathogenic, pathogenic                                 1
benign, likely benign, likely pathogenic                              1
likely pathogenic, pathogenic                                         1
Name: count, dtype: int64

In [9]:
#going to condense the classifcation labels into 4 groups - VUS, Disease Causing, Benign, and NA
#most labels do not have a mix of benign and pathogenic, so we can group them better. If you do have a mix, I would look at the predictions and see were they best align

#breakdown of grouping
#VUS - anything with uncertain in the label (will run this first)
#Disease Causing - pathogenic| likely pathogenic, pathogenic|benign, likely pathogenic, pathogenic| benign, likely benign, likely pathogenic
#Benign - |benign, likely benign | benign | likely benign |
#NA - Not Provided (run last) 

#creating a duplicate of Clinvar_classification to make these changes to, so we can keep the original column
BRCA2_SS["clinvar_CL"] = BRCA2_SS["clinvar_classification"]
BRCA2_SS[["clinvar_CL","clinvar_classification"]].head(5)

C:\Users\knigh\AppData\Local\Temp\ipykernel_136828\1015788729.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  BRCA2_SS["clinvar_CL"] = BRCA2_SS["clinvar_classification"]

,clinvar_CL,clinvar_classification
0,uncertain significance,uncertain significance
1,uncertain significance,uncertain significance
2,"benign, likely benign","benign, likely benign"
3,"likely benign, uncertain significance","likely benign, uncertain significance"
4,"benign, uncertain significance","benign, uncertain significance"

In [10]:
#changing the labels of the clinvar_CL (concordance labels) to match the groups made eariler
#starting with the uncertain group
BRCA2_SS.loc[BRCA2_SS["clinvar_CL"].str.contains("uncertain", na=False), "clinvar_CL"] = "VUS"

#checking the counts, should be 776
BRCA2_SS["clinvar_CL"].value_counts()

clinvar_CL
VUS                                         776
benign, likely benign                        53
likely benign                                 4
benign                                        3
pathogenic                                    2
benign, likely pathogenic, pathogenic         1
benign, likely benign, likely pathogenic      1
likely pathogenic, pathogenic                 1
Name: count, dtype: int64

In [11]:
#now changing the pathogenic rows to be disease causing
BRCA2_SS.loc[BRCA2_SS["clinvar_CL"].str.contains("pathogenic", na=False), "clinvar_CL"] = "Disease Causing"

#checking count, there should be 5
BRCA2_SS["clinvar_CL"].value_counts()

clinvar_CL
VUS                      776
benign, likely benign     53
Disease Causing            5
likely benign              4
benign                     3
Name: count, dtype: int64

In [12]:
#now changing the benign group
BRCA2_SS.loc[BRCA2_SS["clinvar_CL"].str.contains("benign",na=False),"clinvar_CL"] = 'Benign'

#checking count, should be 60
BRCA2_SS["clinvar_CL"].value_counts()

clinvar_CL
VUS                776
Benign              60
Disease Causing      5
Name: count, dtype: int64

In [13]:
#Lastly changing the Not Provide to an NA
BRCA2_SS.loc[BRCA2_SS["clinvar_CL"].str.contains("not provided",na=False),"clinvar_CL"] = pd.NA

#counting NAs, should be 65
print(BRCA2_SS["clinvar_CL"].isna().sum())

#checking full count
BRCA2_SS["clinvar_CL"].value_counts()

#total is 906, same # of rows

65

clinvar_CL
VUS                776
Benign              60
Disease Causing      5
Name: count, dtype: int64

In [14]:
#Now updating the REVEL column
#REVEL has a score scale for their classifications:
#Revel score break down.
#≥ 0.644	Pathogenic supporting
#0.643 - 0.291	Neutral (it is benign leaning, so for concordance purposes we will label as benign)
#≤ 0.290	Benign supporting

#Copying the Revel Column to modify
BRCA2_SS['revel_CL'] = BRCA2_SS['revel']
BRCA2_SS[['revel_CL',"revel"]].head(5)

C:\Users\knigh\AppData\Local\Temp\ipykernel_136828\1168668395.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  BRCA2_SS['revel_CL'] = BRCA2_SS['revel']

   revel_CL  revel
0     0.045  0.045
1     0.103  0.103
2     0.075  0.075
3     0.049  0.049
4     0.057  0.057

In [15]:
#Updating the revel_CL column with the concordance labels

#assigning the revel scores to their labels based on the score scale
BRCA2_SS.loc[BRCA2_SS['revel'] >= .644, 'revel_CL'] = 'Disease Causing'
BRCA2_SS.loc[BRCA2_SS['revel'] <= .643, 'revel_CL'] = 'Benign'

print("Count of Disease causing is", (BRCA2_SS['revel_CL'] == 'Disease Causing').sum())
print("Count of Benign is",(BRCA2_SS['revel_CL'] == 'Benign').sum())

#60 Disease causing, 846 Benign

Count of Disease causing is 60
Count of Benign is 846

C:\Users\knigh\AppData\Local\Temp\ipykernel_136828\4231114198.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Disease Causing' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  BRCA2_SS.loc[BRCA2_SS['revel'] >= .644, 'revel_CL'] = 'Disease Causing'

In [16]:
#Moving on to the Polyphen columns to update them to CLs
#Poly-phen has 3 catagories - Benign, possibly damaging, and probably damanging. We will spilt into two groups Benign and Disease Causing

#copying the three Poly-phen classification columns to modify starting with S1 (student 1)
BRCA2_SS["(HumDiv) Polyphen Significance(S1)_CL"] = BRCA2_SS["(HumDiv) Polyphen Significance(S1)"]
BRCA2_SS[["(HumDiv) Polyphen Significance(S1)_CL", "(HumDiv) Polyphen Significance(S1)"]].head(5)

C:\Users\knigh\AppData\Local\Temp\ipykernel_136828\1566272950.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  BRCA2_SS["(HumDiv) Polyphen Significance(S1)_CL"] = BRCA2_SS["(HumDiv) Polyphen Significance(S1)"]

  (HumDiv) Polyphen Significance(S1)_CL (HumDiv) Polyphen Significance(S1)
0                                benign                             benign
1                     probably damaging                  probably damaging
2                     probably damaging                  probably damaging
3                                benign                             benign
4                                benign                             benign

In [17]:
#now S2 (student 2)
BRCA2_SS["(HumDiv) Polyphen Significance(S2)_CL"] = BRCA2_SS["(HumDiv) Polyphen Significance(S2)"]
BRCA2_SS[["(HumDiv) Polyphen Significance(S2)_CL", "(HumDiv) Polyphen Significance(S2)"]].head(5)

C:\Users\knigh\AppData\Local\Temp\ipykernel_136828\4025801019.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  BRCA2_SS["(HumDiv) Polyphen Significance(S2)_CL"] = BRCA2_SS["(HumDiv) Polyphen Significance(S2)"]

  (HumDiv) Polyphen Significance(S2)_CL (HumDiv) Polyphen Significance(S2)
0                                benign                             benign
1                    probably damaging                  probably damaging
2                    probably damaging                  probably damaging
3                               benign                             benign
4                                benign                             benign

In [18]:
#now S3 (S3)
BRCA2_SS["(HumDiv) Polyphen Significance(S3)_CL"] = BRCA2_SS["(HumDiv) Polyphen Significance(S3)"]
BRCA2_SS[["(HumDiv) Polyphen Significance(S3)_CL", "(HumDiv) Polyphen Significance(S3)"]].head(5)

C:\Users\knigh\AppData\Local\Temp\ipykernel_136828\2897913715.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  BRCA2_SS["(HumDiv) Polyphen Significance(S3)_CL"] = BRCA2_SS["(HumDiv) Polyphen Significance(S3)"]

  (HumDiv) Polyphen Significance(S3)_CL (HumDiv) Polyphen Significance(S3)
0                                benign                             benign
1                     probably damaging                  probably damaging
2                     probably damaging                  probably damaging
3                                benign                             benign
4                                benign                             benign

In [19]:
#updating the Poly-phen classifications to CLs

#starting with (HumDiv) Polyphen Significance(S1)
#We already have a benign classification, so we only need to updating the damaging classes to disease causing
BRCA2_SS.loc[BRCA2_SS["(HumDiv) Polyphen Significance(S1)"].str.lower().str.contains("Damaging",na=False),"(HumDiv) Polyphen Significance(S1)_CL"] = 'Disease Causing'
#not sure hy Damaging won't capture them all, but using both upper and lower case seems to work
BRCA2_SS.loc[BRCA2_SS["(HumDiv) Polyphen Significance(S1)"].str.lower().str.contains("damaging",na=False),"(HumDiv) Polyphen Significance(S1)_CL"] = 'Disease Causing'
BRCA2_SS.loc[BRCA2_SS["(HumDiv) Polyphen Significance(S1)"].str.lower().str.contains("benign",na=False),"(HumDiv) Polyphen Significance(S1)_CL"] = 'Benign'

#Next (HumDiv) Polyphen Significance(S2)
BRCA2_SS.loc[BRCA2_SS["(HumDiv) Polyphen Significance(S2)"].str.lower().str.contains("Damaging",na=False),"(HumDiv) Polyphen Significance(S2)_CL"] = 'Disease Causing'
BRCA2_SS.loc[BRCA2_SS["(HumDiv) Polyphen Significance(S2)"].str.lower().str.contains("damaging",na=False),"(HumDiv) Polyphen Significance(S2)_CL"] = 'Disease Causing'
BRCA2_SS.loc[BRCA2_SS["(HumDiv) Polyphen Significance(S2)"].str.lower().str.contains("benign",na=False),"(HumDiv) Polyphen Significance(S2)_CL"] = 'Benign'

#Next (HumDiv) Polyphen Significance(S3)
BRCA2_SS.loc[BRCA2_SS["(HumDiv) Polyphen Significance(S3)"].str.lower().str.contains("Damaging",na=False),"(HumDiv) Polyphen Significance(S3)_CL"] = 'Disease Causing'
BRCA2_SS.loc[BRCA2_SS["(HumDiv) Polyphen Significance(S3)"].str.lower().str.contains("damaging",na=False),"(HumDiv) Polyphen Significance(S3)_CL"] = 'Disease Causing'
BRCA2_SS.loc[BRCA2_SS["(HumDiv) Polyphen Significance(S3)"].str.lower().str.contains("benign",na=False),"(HumDiv) Polyphen Significance(S3)_CL"] = 'Benign'


#comparing counts
BRCA2_SS["(HumDiv) Polyphen Significance(S1)_CL"].value_counts()

(HumDiv) Polyphen Significance(S1)_CL
Benign                  538
Disease Causing         367
Error: Malformed XML      1
Name: count, dtype: int64

In [20]:
BRCA2_SS["(HumDiv) Polyphen Significance(S2)_CL"].value_counts()

(HumDiv) Polyphen Significance(S2)_CL
Benign                  440
Disease Causing         208
Error: Malformed XML      1
Name: count, dtype: int64

In [21]:
BRCA2_SS["(HumDiv) Polyphen Significance(S3)_CL"].value_counts()

(HumDiv) Polyphen Significance(S3)_CL
Benign                  538
Disease Causing         367
Error: Malformed XML      1
Name: count, dtype: int64

### All columns are now updated

## Comparing Corcordance Labels between Poly-phen, in-silco tools, and Cinvar

## Comparing Poly-phen student scores first

In [22]:
#taking student 1, 2 and 3 poly-phen columns that we updated eariler with concordance labels and comparing them against eachother

PP_CL_Total = (
    (BRCA2_SS["(HumDiv) Polyphen Significance(S1)_CL"] == BRCA2_SS["(HumDiv) Polyphen Significance(S3)_CL"]) &
    (
        BRCA2_SS["(HumDiv) Polyphen Significance(S2)_CL"].isna() | #this prevents the missing values in S2 to count as discordance since there was alot
        (BRCA2_SS["(HumDiv) Polyphen Significance(S2)_CL"] == BRCA2_SS["(HumDiv) Polyphen Significance(S1)_CL"])
    )
).sum()

print(PP_CL_Total)

#904 concordant predictions

904

In [23]:
#looking at the discordance between students
cols = [
    "(HumDiv) Polyphen Significance(S1)_CL",
    "(HumDiv) Polyphen Significance(S2)_CL",
    "(HumDiv) Polyphen Significance(S3)_CL"
]

# Rows where the non-missing values do not all agree
rows_disagree = BRCA2_SS[BRCA2_SS[cols].nunique(axis=1) > 1]

rows_disagree[cols].head(5)

#looked at variants in rows 672 and 752 and looked them up on polyPhen-2 separately
#672: Disease Causing
#752: Benign

#very weird, I double checked the Polyphen full report and confirmed S3 values, but when I input the variants manually one by one, the value was different depending if input as a single submission or batch

,(HumDiv) Polyphen Significance(S1)_CL,(HumDiv) Polyphen Significance(S2)_CL,(HumDiv) Polyphen Significance(S3)_CL
672,Disease Causing,NaN,Benign
752,Benign,NaN,Disease Causing

In [24]:
#was not able to compare student scores as I was in BRCA1, there was too many differences between the values formats entered and time became limited. 
#But still compared labels and scores for every variant was able to be pulled from PolyPhen using the Batch submissions and parsing to tabluar form for merging

### Comparing Polyphen to Clinvar

In [25]:
#since the labels for S1 were more acurrate, I will just use the S1 column for comparision
print((BRCA2_SS["clinvar_CL"] == BRCA2_SS["(HumDiv) Polyphen Significance(S1)_CL"]).sum())

#looking at the discordance
BRCA2_SS.loc[(BRCA2_SS["clinvar_CL"].isin(["Benign", "Disease Causing"])) & 
    (BRCA2_SS["clinvar_CL"] != BRCA2_SS["(HumDiv) Polyphen Significance(S1)_CL"]),["clinvar_CL", "(HumDiv) Polyphen Significance(S1)_CL"]]

#Clinvar and Polyphen align for 48 values. That is 73.85% of clinvar that is not VUS or missing

48

    clinvar_CL (HumDiv) Polyphen Significance(S1)_CL
2       Benign                       Disease Causing
181     Benign                       Disease Causing
247     Benign                       Disease Causing
283     Benign                       Disease Causing
304     Benign                       Disease Causing
337     Benign                       Disease Causing
352     Benign                       Disease Causing
532     Benign                       Disease Causing
561     Benign                       Disease Causing
600     Benign                       Disease Causing
607     Benign                       Disease Causing
620     Benign                       Disease Causing
724     Benign                       Disease Causing
766     Benign                       Disease Causing
773     Benign                       Disease Causing
794     Benign                       Disease Causing
891     Benign                       Disease Causing

In [ ]:
#looking at the concordance between Clinvar and Polyphen
ClinPolconcord = BRCA2_SS.loc[BRCA2_SS["clinvar_CL"] == BRCA2_SS["(HumDiv) Polyphen Significance(S1)_CL"],["clinvar_CL", "(HumDiv) Polyphen Significance(S1)_CL"]]
ClinPolconcord.value_counts()

clinvar_CL       (HumDiv) Polyphen Significance(S1)_CL
Benign           Benign                                   43
Disease Causing  Disease Causing                           5
Name: count, dtype: int64

### Comparing PolyPhen to Revel

In [26]:
#Finding how many time Polyphen labels match Clinvar labels
print((BRCA2_SS["revel_CL"] == BRCA2_SS["(HumDiv) Polyphen Significance(S1)_CL"]).sum())

#looking at the discordance
BRCA2_SS.loc[(BRCA2_SS["revel_CL"] != BRCA2_SS["(HumDiv) Polyphen Significance(S1)_CL"]),
             ["revel_CL", "(HumDiv) Polyphen Significance(S1)_CL"]]

#596 concordant, 65.78% concordant, 310 discordant

596

    revel_CL (HumDiv) Polyphen Significance(S1)_CL
1     Benign                       Disease Causing
2     Benign                       Disease Causing
5     Benign                       Disease Causing
6     Benign                       Disease Causing
7     Benign                       Disease Causing
..       ...                                   ...
888   Benign                       Disease Causing
889   Benign                       Disease Causing
890   Benign                       Disease Causing
891   Benign                       Disease Causing
903   Benign                       Disease Causing

[310 rows x 2 columns]

In [ ]:
#looking at the concordance between polyphen and REVEL
Wmodelconcord = BRCA2_SS.loc[(BRCA2_SS["revel_CL"] == BRCA2_SS["(HumDiv) Polyphen Significance(S1)_CL"]),["revel_CL", "(HumDiv) Polyphen Significance(S1)_CL"]]
Wmodelconcord.value_counts()

revel_CL         (HumDiv) Polyphen Significance(S1)_CL
Benign           Benign                                   537
Disease Causing  Disease Causing                           59
Name: count, dtype: int64

### Comparing Revel to Clinvar

In [27]:
#Finding how many time REVEL labels match Clinvar labels
print((BRCA2_SS["clinvar_CL"] == BRCA2_SS["revel_CL"]).sum())

#looking at the discordance
BRCA2_SS.loc[(BRCA2_SS["clinvar_CL"].isin(["Benign", "Disease Causing"])) & #this line is here to skip over the VUS classifications
    (BRCA2_SS["clinvar_CL"] != BRCA2_SS["revel_CL"]),["clinvar_CL", "revel_CL"]]

#clinvar and revel align for 63 non-VUS/missing values out of 65, 96.9% concordant!!

63

          clinvar_CL         revel_CL
607           Benign  Disease Causing
788  Disease Causing           Benign

In [ ]:
#looking at the concordance between Clinvar and REVEL
ClinRevconcord = BRCA2_SS.loc[BRCA2_SS["clinvar_CL"] == BRCA2_SS["revel_CL"],["clinvar_CL", "revel_CL"]]
ClinRevconcord.value_counts()

clinvar_CL       revel_CL
Benign           Benign             59
Disease Causing  Disease Causing     4
Name: count, dtype: int64

### Adding the created labels back onto the original df for exporting to model with in another script

In [ ]:
#Keeping only the key col and the newly added lablel columns from the subset
cols_to_move = ['vid', 'clinvar_CL', 'revel_CL', 
               '(HumDiv) Polyphen Significance(S1)_CL', 
               '(HumDiv) Polyphen Significance(S2)_CL',
               '(HumDiv) Polyphen Significance(S3)_CL']

#separating the label columns from BRCA2_SS df
subset = BRCA2_SS[cols_to_move]

#Merge with original dataframe on 'vid', new dataset so orignial and label df remains unchanged
df2_final = BRCA2_UG_AN.merge(subset, on='vid', how='left')

#looking at df
df2_final.head()

#Data Preview removed to comply with All of Us data user policies.

In [29]:
df2_final.to_csv("C:/Users/knigh/Documents/UHD MSDA/Capstone/Concordance/2026_BRCA2_ConcordanceLabels.csv")